# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
