# Generated by Django 6.0.6 on 2026-06-22 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type', models.CharField(choices=[('sunflower', 'Sunflower'), ('tulip', 'Tulip'), ('daisy', 'Daisy'), ('strawberry', 'Strawberry'), ('herb', 'Herb')], max_length=32)),
                ('state', models.CharField(choices=[('seed', 'Seed'), ('growing', 'Growing'), ('flower', 'Flower'), ('bud', 'Bud')], default='seed', max_length=16)),
                ('planted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='garden.gardenslot')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot__slot_number'],
            },
        ),
    ]
