# Generated by Django 6.0.1 on 2026-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='seed_type',
            field=models.CharField(choices=[('rose', 'Rose'), ('sunflower', 'Sunflower'), ('tulip', 'Tulip'), ('daisy', 'Daisy'), ('lavender', 'Lavender'), ('lily', 'Lily'), ('orchid', 'Orchid'), ('cherry_blossom', 'Cherry Blossom'), ('bluebell', 'Bluebell'), ('peony', 'Peony'), ('hibiscus', 'Hibiscus'), ('lotus', 'Lotus'), ('marigold', 'Marigold'), ('poppy', 'Poppy'), ('hydrangea', 'Hydrangea'), ('cactus', 'Cactus'), ('aloe', 'Aloe'), ('strawberry', 'Strawberry'), ('mint', 'Mint'), ('basil', 'Basil'), ('herb', 'Herb')], max_length=32),
        ),
    ]
