# Generated by Django 6.0.1 on 2026-07-01 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_alter_plant_seed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant', to='garden.gardenslot'),
        ),
    ]
