# Generated by Django 6.0.1 on 2026-06-21 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('estimated_duration', models.PositiveIntegerField()),
                ('seed_type', models.CharField(choices=[('sunflower', 'Sunflower'), ('tulip', 'Tulip'), ('daisy', 'Daisy'), ('strawberry', 'Strawberry'), ('herb', 'Herb')], max_length=32)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('planted', 'Planted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partial', 'Partial')], default='stored', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_watered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
            ],
        ),
    ]
