# Generated by Django 6.0.1 on 2026-06-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_seed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='seed_type',
            field=models.CharField(choices=[('rose', 'Rose'), ('sunflower', 'Sunflower'), ('tulip', 'Tulip'), ('white_daisy', 'White Daisy'), ('pink_peony', 'Pink Peony'), ('love_in_a_mist', 'Love-in-a-Mist'), ('lavender', 'Lavender'), ('lily', 'Lily'), ('spider_lily', 'Spider Lily'), ('purple_daisy', 'Purple Daisy'), ('hibiscus', 'Hibiscus'), ('hydrangea', 'Hydrangea'), ('gladiolus', 'Gladiolus'), ('calla_lilies', 'Calla Lilies'), ('yellow_iris', 'Yellow Iris'), ('red_anemones', 'Red Anemones'), ('candy_cane_sorrel', 'Candy Cane Sorrel')], max_length=32),
        ),
    ]
